name: Waystones
version: ${project.version}
main: de.flo56958.waystones.Main
api-version: 1.13
authors: [Flo56958]
description: A survival immersive warping alternative.

softdepend:
  - Vault

permissions:
  waystones.*:
    children:
      waystones.place: true
      waystones.use: true
      waystones.warpscroll.use: true
      waystones.gobal: true
      waystones.admin: true

  waystones.admin:
    children:
      waystones.global: true
    default: false

  waystones.gobal:
    children:
      waystones.place: true
    default: false

  waystones.place:
    children:
      waystones.discover: true
    default: true

  waystones.discover:
    children:
      waystones.use: true
      waystones.warpscroll.use: true
    default: true

  waystones.use:
    default: true

  waystones.warpscroll.use:
    default: true