name: Waystones
version: ${project.version}
main: de.flo56958.waystones.Main
api-version: 1.13
authors: [Flo56958]
description: A survival immersive warping alternative.

permissions:
  waystones.*:
    children:
      waystones.place: true
      waystones.use: true
      waystones.warpscroll.use: true

  waystones.use:
    default: true

  waystones.warpscroll.use:
    default: true

  waystones.place:
    children:
      waystones.discover: true
    default: true

  waystones.discover:
    default: true