name: Warpstones
version: ${project.version}
main: de.flo56958.warpstones.Main
api-version: 1.13
authors: [Flo56958]
description: A survival immersive warping alternative.

softdepend:
  - Vault

commands:
  warpstones:
    aliases: [ws]
    description: Main Command of Warpstones
    usage: /warpstones [sub]

permissions:
  warpstones.*:
    children:
      warpstones.place: true
      warpstones.use: true
      warpstones.warpscroll.use: true
      warpstones.gobal: true
      warpstones.admin: true
      warpstones.commands.*: true

  warpstones.commands.*:
    children:
      warpstones.commands.main: true
      warpstones.commands.give: true
      warpstones.commands.listallwaypoints: true

  warpstones.commands.main:
    default: true

  warpstones.commands.give:
    children:
      warpstones.commands.main: true
    default: op

  warpstones.commands.listallwaypoints:
    children:
      warpstones.commands.main: true
    default: op

  warpstones.admin:
    children:
      warpstones.global: true
    default: op

  warpstones.gobal:
    children:
      warpstones.place: true
    default: false

  warpstones.place:
    children:
      warpstones.discover: true
    default: true

  warpstones.discover:
    children:
      warpstones.use: true
      warpstones.warpscroll.use: true
    default: true

  warpstones.use:
    default: true

  warpstones.warpscroll.use:
    default: true